;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+CategoryRemapping=(BaseCategory="",RemapCategories=)
+GameplayTagTableList=None
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="World.Season.Winter",NewTagName="World.Season.Frostwane")
+GameplayTagRedirects=(OldTagName="World.Season.Autumn",NewTagName="World.Season.Amberfall")
+GameplayTagRedirects=(OldTagName="World.Season.Summer",NewTagName="World.Season.Suncrest")
+GameplayTagRedirects=(OldTagName="World.Season.Spring",NewTagName="World.Season.Springtide")
+GameplayTagRedirects=(OldTagName="World.Time.Day",NewTagName="World.Time.Morning")
+GameplayTagRedirects=(OldTagName="World.Time.LateNight",NewTagName="World.Time.DarkestHour")
+GameplayTagList=(Tag="Almanac.Type.Artifacts",DevComment="Journal List of Artifacts")
+GameplayTagList=(Tag="Almanac.Type.Bugs",DevComment="Journal List of Bugs")
+GameplayTagList=(Tag="Almanac.Type.Crops",DevComment="Journal List of Crops")
+GameplayTagList=(Tag="Almanac.Type.Fish",DevComment="Journal List of Fish")
+GameplayTagList=(Tag="Almanac.Type.Foraging",DevComment="Journal List of Foragables")
+GameplayTagList=(Tag="CT.Activity.Civic.Protesting",DevComment="Participating in a protest")
+GameplayTagList=(Tag="CT.Activity.Leisure.Sightseeing",DevComment="Touring or sightseeing")
+GameplayTagList=(Tag="CT.Activity.Performance.Busking",DevComment="Street performance or busking")
+GameplayTagList=(Tag="CT.Activity.Social.Drinking",DevComment="Drinking socially")
+GameplayTagList=(Tag="CT.Activity.Social.DrinkingAlone",DevComment="Drinking alone")
+GameplayTagList=(Tag="CT.Activity.Social.GoofingOff",DevComment="Avoiding work, fooling around")
+GameplayTagList=(Tag="CT.Activity.Social.Socializing",DevComment="Casual social interaction")
+GameplayTagList=(Tag="CT.Activity.Study.Studying",DevComment="Studying or research")
+GameplayTagList=(Tag="CT.Activity.Work.Bartending",DevComment="Working as a bartender")
+GameplayTagList=(Tag="CT.Activity.Work.Clerical",DevComment="Administrative or clerical work")
+GameplayTagList=(Tag="CT.Activity.Work.Politicking",DevComment="Political maneuvering or meetings")
+GameplayTagList=(Tag="CT.Activity.Work.Teaching",DevComment="Teaching students")
+GameplayTagList=(Tag="CT.Activity.Work.Volunteering",DevComment="Volunteering civic labor")
+GameplayTagList=(Tag="CT.Location.Town.Castle",DevComment="NPC is at the Castle")
+GameplayTagList=(Tag="CT.Location.Town.MagicAcademy",DevComment="NPC is at the Magic Academy")
+GameplayTagList=(Tag="CT.Location.Town.Plaza",DevComment="NPC is at the Town Plaza")
+GameplayTagList=(Tag="CT.Location.Town.Tavern",DevComment="NPC is at the Tavern")
+GameplayTagList=(Tag="CT.Location.Town.TownHall",DevComment="NPC is at Town Hall")
+GameplayTagList=(Tag="Debug.TestFlag",DevComment="Test flag for debug overlay")
+GameplayTagList=(Tag="Faction.*.Disposition.*",DevComment="Faction Disposition toward Player")
+GameplayTagList=(Tag="Faction.*.Rank.*",DevComment="Rank within Faction")
+GameplayTagList=(Tag="Faction.Merchants",DevComment="Merchant Faction")
+GameplayTagList=(Tag="Faction.Royalist",DevComment="Royalist Faction")
+GameplayTagList=(Tag="Faction.SeekersOfTheVeil",DevComment="Scholar Faction")
+GameplayTagList=(Tag="Faction.ShadowRebels",DevComment="Rebel Faction")
+GameplayTagList=(Tag="Faction.Traditionalists",DevComment="Traditionalists Faction")
+GameplayTagList=(Tag="Faction.WitheredCourt",DevComment="Withered Court Faction")
+GameplayTagList=(Tag="Form.Active.Abime",DevComment="Water Chevalier Form")
+GameplayTagList=(Tag="Form.Active.Aube",DevComment="Dawn Chevalier Form")
+GameplayTagList=(Tag="Form.Active.Crepuscule",DevComment="Twilight Chevalier Form")
+GameplayTagList=(Tag="Form.Active.Flammes",DevComment="Fire Chevalier Form")
+GameplayTagList=(Tag="Form.Active.Givre",DevComment="Frost Chevalier Form")
+GameplayTagList=(Tag="Form.Active.Hasard",DevComment="Trickster Chevalier Form")
+GameplayTagList=(Tag="Form.Active.None",DevComment="Chevalier Form Active")
+GameplayTagList=(Tag="Form.Active.Nuit",DevComment="Night Chevalier Form")
+GameplayTagList=(Tag="Form.Active.Tempete",DevComment="Storm Chevalier Form")
+GameplayTagList=(Tag="Form.Active.Temps",DevComment="Time Chevalier Form")
+GameplayTagList=(Tag="Form.Active.Vent",DevComment="Wind Chevalier Form")
+GameplayTagList=(Tag="Form.Active.Vie",DevComment="Plant Chevalier Form")
+GameplayTagList=(Tag="Form.Active.Voile",DevComment="Shadow Chevalier Form")
+GameplayTagList=(Tag="Form.State.Mastered",DevComment="Mastery of a Chevalier Form")
+GameplayTagList=(Tag="Form.State.TransformingIn",DevComment="Transforming into Chevalier")
+GameplayTagList=(Tag="Form.State.TransformingOut",DevComment="Transforming out of Chevalier")
+GameplayTagList=(Tag="Journal.Tab.Almanac",DevComment="Almanac Tab of Journal")
+GameplayTagList=(Tag="Journal.Tab.Artifacts",DevComment="Artifact Tab of Journal")
+GameplayTagList=(Tag="Journal.Tab.Lore",DevComment="Lore Tab of Journal")
+GameplayTagList=(Tag="Journal.Tab.NPCs",DevComment="NPC Tab of Journal")
+GameplayTagList=(Tag="Journal.Tab.Quests",DevComment="Quest Tab of Journal")
+GameplayTagList=(Tag="Journal.Tab.Rumors",DevComment="Rumor Tab of Journal")
+GameplayTagList=(Tag="Journal.Tab.WorldAtlas",DevComment="Map Tab of Journal")
+GameplayTagList=(Tag="Knowledge.Cycle.Known",DevComment="Knowledge of Cycle")
+GameplayTagList=(Tag="Knowledge.SecretIdentity.Known",DevComment="Knowledge of Secret Identity")
+GameplayTagList=(Tag="Knowledge.SecretIdentity.KnownBy.<NPCID>",DevComment="Knowledge of Secret Identity by this NPC")
+GameplayTagList=(Tag="Knowledge.Watcher.Known",DevComment="Knowledge of Watcher")
+GameplayTagList=(Tag="Lumen.Blood",DevComment="Sacrifice Magic")
+GameplayTagList=(Tag="Lumen.Celestial",DevComment="Star Magic")
+GameplayTagList=(Tag="Lumen.Chrono",DevComment="Time Magic")
+GameplayTagList=(Tag="Lumen.Ember",DevComment="Fire Magic")
+GameplayTagList=(Tag="Lumen.Frost",DevComment="Ice Magic")
+GameplayTagList=(Tag="Lumen.Glimmer",DevComment="Light Magic")
+GameplayTagList=(Tag="Lumen.Hollow",DevComment="Darkness Magic")
+GameplayTagList=(Tag="Lumen.Ripple",DevComment="Water Magic")
+GameplayTagList=(Tag="Lumen.Surge",DevComment="Lightning Magic")
+GameplayTagList=(Tag="Lumen.Verdant",DevComment="Nature Magic")
+GameplayTagList=(Tag="Lumen.Zephyr",DevComment="Air Magic")
+GameplayTagList=(Tag="NPC.Test.Met",DevComment="")
+GameplayTagList=(Tag="Player.State.InCombat",DevComment="Player engaged in combat")
+GameplayTagList=(Tag="Player.State.InDialogue",DevComment="Player currently in dialogue")
+GameplayTagList=(Tag="Player.State.InJournal",DevComment="Player currently in journal")
+GameplayTagList=(Tag="Player.State.Resting",DevComment="Player resting.")
+GameplayTagList=(Tag="Player.State.Stealth",DevComment="Player currently engaged in stealth ")
+GameplayTagList=(Tag="Player.State.Underwater",DevComment="Player currently underwater")
+GameplayTagList=(Tag="Quest.State.Active",DevComment="Active Quest")
+GameplayTagList=(Tag="Quest.State.Available",DevComment="Available Quest")
+GameplayTagList=(Tag="Quest.State.Completed",DevComment="Completed Quest")
+GameplayTagList=(Tag="Quest.State.Failed",DevComment="Failed Quest")
+GameplayTagList=(Tag="Quest.State.Hidden",DevComment="Hidden Quest")
+GameplayTagList=(Tag="World.Cycle.Anomaly.Active",DevComment="World Status: Cycle Anomaly is Active")
+GameplayTagList=(Tag="World.Cycle.Echo.Visible",DevComment="World Status: Cycle Echo is Visible")
+GameplayTagList=(Tag="World.Cycle.HintSeen",DevComment="Player has seen a cycle hint")
+GameplayTagList=(Tag="World.Cycle.NG",DevComment="World Status: First Cycle")
+GameplayTagList=(Tag="World.Cycle.NGPlus",DevComment="World Status: New Game Plus")
+GameplayTagList=(Tag="World.Cycle.NGPlusPlus",DevComment="World Status: New Game Plus Plus")
+GameplayTagList=(Tag="World.Event.Festival.Active",DevComment="World Event: Festival Active")
+GameplayTagList=(Tag="World.Event.TownMeeting.Active",DevComment="World Event: Town Meeting Active")
+GameplayTagList=(Tag="World.Event.TravelersMarket.Active",DevComment="World Event: Market Active")
+GameplayTagList=(Tag="World.Region.DawnlightFields",DevComment="Region is Dawnlight Fields.")
+GameplayTagList=(Tag="World.Region.DrownedSanctum",DevComment="Region is Drowned Sanctum.")
+GameplayTagList=(Tag="World.Region.EchoingGlade",DevComment="Region is Echoing Glade.")
+GameplayTagList=(Tag="World.Region.EmberHighlands",DevComment="Region is Ember Highlands.")
+GameplayTagList=(Tag="World.Region.FarlightVale",DevComment="Region is Farlight Vale.")
+GameplayTagList=(Tag="World.Region.FrozenVeil",DevComment="Region is Frozen Veil.")
+GameplayTagList=(Tag="World.Region.LuminousChasm",DevComment="Region is Luminous Chasm.")
+GameplayTagList=(Tag="World.Region.ShimmeringShores",DevComment="Region is Shimmering Shores.")
+GameplayTagList=(Tag="World.Season.Amberfall",DevComment="Season is Fall")
+GameplayTagList=(Tag="World.Season.Frostwane",DevComment="Season is Winter")
+GameplayTagList=(Tag="World.Season.Springtide",DevComment="Season is Spring")
+GameplayTagList=(Tag="World.Season.Suncrest",DevComment="Season is Summer")
+GameplayTagList=(Tag="World.Time.Afternoon",DevComment="Time is Afternoon")
+GameplayTagList=(Tag="World.Time.DarkestHour",DevComment="Time is Darkest Hour (post-midnight)")
+GameplayTagList=(Tag="World.Time.Dawn",DevComment="Time is Dawn")
+GameplayTagList=(Tag="World.Time.Dusk",DevComment="Time is Dusk")
+GameplayTagList=(Tag="World.Time.Evening",DevComment="Time is Evening")
+GameplayTagList=(Tag="World.Time.Midday",DevComment="Time is Midday")
+GameplayTagList=(Tag="World.Time.Morning",DevComment="Time is Morning")
+GameplayTagList=(Tag="World.Time.Night",DevComment="Time is Night")

